FROM node:20-alpine

# Install Redis
RUN apk add --no-cache redis

WORKDIR /app

COPY package*.json ./
RUN npm ci --legacy-peer-deps

COPY . .

# Generate Prisma client & build TypeScript
RUN npx prisma generate
RUN npm run build

COPY start.sh .
RUN chmod +x start.sh

EXPOSE 4000

CMD ["./start.sh"]