ALTER TYPE "POStatus" ADD VALUE IF NOT EXISTS 'READY_FOR_DISPATCH';
ALTER TYPE "POStatus" ADD VALUE IF NOT EXISTS 'COMPLETED';
ALTER TYPE "MessageType" ADD VALUE IF NOT EXISTS 'ORDER_READY_FOR_DISPATCH';
ALTER TYPE "MessageType" ADD VALUE IF NOT EXISTS 'ORDER_DISPATCHED';
ALTER TYPE "MessageType" ADD VALUE IF NOT EXISTS 'ORDER_DELIVERED';
ALTER TYPE "MessageType" ADD VALUE IF NOT EXISTS 'ORDER_RECEIVED';

ALTER TABLE "PurchaseOrder"
  ADD COLUMN IF NOT EXISTS "readyForDispatchAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "dispatchedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "buyerConfirmedAt" TIMESTAMP(3);
