ALTER TYPE "POStatus" ADD VALUE IF NOT EXISTS 'PREPARING';
ALTER TYPE "MessageType" ADD VALUE IF NOT EXISTS 'ORDER_PREPARING';

ALTER TABLE "PurchaseOrder" ADD COLUMN IF NOT EXISTS "preparingAt" TIMESTAMP(3);
