ALTER TYPE "RfqStatus" ADD VALUE IF NOT EXISTS 'NEGOTIATION_ACCEPTED';
ALTER TYPE "MessageType" ADD VALUE IF NOT EXISTS 'ORDER_CREATED';
ALTER TYPE "MessageType" ADD VALUE IF NOT EXISTS 'PAYMENT_UPDATE';

ALTER TABLE "RequestForQuotation"
  ADD COLUMN IF NOT EXISTS "agentAcceptedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "supplierAcceptedAt" TIMESTAMP(3);
ALTER TABLE "NegotiationOffer"
  ADD COLUMN IF NOT EXISTS "minimumOrderQuantity" INTEGER,
  ADD COLUMN IF NOT EXISTS "estimatedLeadTime" TEXT,
  ADD COLUMN IF NOT EXISTS "validUntil" TIMESTAMP(3);
ALTER TABLE "ConversationMessage"
  ADD COLUMN IF NOT EXISTS "deliveredAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "seenAt" TIMESTAMP(3);
